services:
  coordinator:
    build:
      context: ./src
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: gunicorn -w 2 -b 0.0.0.0:5000 app.api.main:app

  worker-recon:
    build:
      context: ./src
    depends_on:
      - redis
    command: python3 -m app.agents.recon

  worker-web:
    build:
      context: ./src
    depends_on:
      - redis
    command: python3 -m app.agents.web

  worker-vuln:
    build:
      context: ./src
    depends_on:
      - redis
    command: python3 -m app.agents.vuln

  redis:
    image: redis:7-alpine


  db:
    # This database service is used only for local development
    # Note: It may be preferable to use an online database service
    # https://db.anotherwebservice.com/
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_database

  phpmyadmin:
    # To view the database during local development
    # Visit http://127.0.0.1:8080/
    # Server is: db
    # Username is same as MYSQL_USER
    # Password is same as MYSQL_PASSWORD
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: "1"
